# Generated by Django 2.2.6 on 2021-04-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='LandingBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текстовый блок'), ('news', 'Новостной блок'), ('comment', 'Комментарий'), ('gallery', 'Фото галерея'), ('feedback', 'Отзывы')], default='text', max_length=100, verbose_name='Тип блока')),
                ('npp', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.LandingPage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('npp',),
            },
        ),
    ]
