# Generated by Django 2.2.6 on 2021-04-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
